version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'jooq_example'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sample_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '30001:3306'
    expose:
      # Opens port 3306 on the container
      - '30001'
      # Where our data will be persisted
    volumes:
      - spring-jooq-example-mysql:/var/lib/mysql

  controller:
    image: ngrinder/controller
    restart: always
    ports:
      - "30010:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - spring-jooq-example-ngrinder:/opt/ngrinder-controller

  agent:
    image: ngrinder/agent
    restart: always
    links:
      - controller

# Names our volume
volumes:
  spring-jooq-example-mysql:
  spring-jooq-example-ngrinder:
