/*
 * This file is generated by jOOQ.
 */
package co.lopun.core.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shop implements Serializable {

    private static final long serialVersionUID = -1925684101;

    private final Integer       id;
    private final String        name;
    private final String        url;
    private final LocalDateTime createdAt;
    private final LocalDateTime updatedAt;

    public Shop(Shop value) {
        this.id = value.id;
        this.name = value.name;
        this.url = value.url;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Shop(
        Integer       id,
        String        name,
        String        url,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.name = name;
        this.url = url;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Integer getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public String getUrl() {
        return this.url;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Shop (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(url);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
