/*
 * This file is generated by jOOQ.
 */
package co.lopun.core.model.tables.records;


import co.lopun.core.model.tables.Shop;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopRecord extends UpdatableRecordImpl<ShopRecord> implements Record5<Integer, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1879941356;

    /**
     * Setter for <code>jooq_example.shop.id</code>.
     */
    public ShopRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jooq_example.shop.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooq_example.shop.name</code>.
     */
    public ShopRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jooq_example.shop.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq_example.shop.url</code>.
     */
    public ShopRecord setUrl(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jooq_example.shop.url</code>.
     */
    public String getUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jooq_example.shop.created_at</code>.
     */
    public ShopRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jooq_example.shop.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>jooq_example.shop.updated_at</code>.
     */
    public ShopRecord setUpdatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jooq_example.shop.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Shop.SHOP.ID;
    }

    @Override
    public Field<String> field2() {
        return Shop.SHOP.NAME;
    }

    @Override
    public Field<String> field3() {
        return Shop.SHOP.URL;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Shop.SHOP.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Shop.SHOP.UPDATED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getUrl();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getUrl();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public ShopRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ShopRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ShopRecord value3(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public ShopRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ShopRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public ShopRecord values(Integer value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShopRecord
     */
    public ShopRecord() {
        super(Shop.SHOP);
    }

    /**
     * Create a detached, initialised ShopRecord
     */
    public ShopRecord(Integer id, String name, String url, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Shop.SHOP);

        set(0, id);
        set(1, name);
        set(2, url);
        set(3, createdAt);
        set(4, updatedAt);
    }
}
