server:
  port: 30002
  tomcat:
    threads:
      max: 512

logging:
  level:
    root: INFO

spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: mysql
    database_platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate_ddl: true
    hibernate:
      ddl_auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
  datasource:
    replica:
      url: jdbc:mysql://localhost:30001/jooq_example?serverTimezone=Asia/Seoul
    master:
      url: jdbc:mysql://localhost:30001/jooq_example?serverTimezone=Asia/Seoul
    username: sample_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
